### ISSUE TITLE
Unable to extract normalized counts

### ISSUE THREAD

**Issue by arvchi** [drisso/zinbwave#11]
I am trying zinbwave on a set of gene expression data.  I succeeded in creating a ZinbModel object by using the function zinbFit. This also worked for subsequent tSNE visualisation.

However, I want to extract the normalised counts to use for heatmaps and other visualisations. I try the following code belowe, but it doesn't work. I get the error message: "Error in (function (classes, fdef, mtable)
: unable to find an inherited method for function ‘zinbwave’ for signature ‘"ZinbModel"". I have also tried using just the count matrix input and re-do the fitting, but it still gives error.

```r
# Create zinbwave object
  ## filter low abundance
  filter <- rowSums(rawCountMatrix>5)>5
  counts_filtered <- rawCountMatrix[filter,]
  
  ## Identify and select top 1000 variable genes
  counts_filtered %>% log1p %>% rowVars -> vars
  names(vars) <- rownames(counts_filtered)
  vars <- sort(vars, decreasing = TRUE)
  counts_filtered <- counts_filtered[names(vars)[1:1000],]

  ## Create SE object
  se <- SummarizedExperiment(counts_filtered,
                           colData = data.frame(colnames(rawCountTable),condition_mod,row.names = 1))
  
  ## Apply zinbFit function
  zinb <- zinbFit(se, K=2, epsilon=1000)
  
  ## Get normalized values
  se_norm <- zinbwave(zinb, fitted_model=zinb, normalizedValues=TRUE, residuals = TRUE)
```

**Comment by drisso** [comment]
Hi @arvchi 

Your code has a problem in the last line. The first argument of `zinbwave` should be a `SummarizedExperiment` object. 

I will change the documentation to make that clearer.

If you substitute your last line with
```{r}
se_norm <- zinbwave(se, fitted_model=zinb, normalizedValues=TRUE, residuals = TRUE)
```

It should work.
