### ISSUE TITLE
Y matrix in function zinbFit

### ISSUE THREAD

**Issue by CcYyQq** [drisso/zinbwave#13]
Hi，
      I build a SummarizedExperiment object using my own data to run the tutorial guide of zinbwave.  And always encounter the same question. I don't know what's wrong with it and how to solve.
      Thank you.

![_20180130224945](https://user-images.githubusercontent.com/34188141/35572604-f0bbd9de-060f-11e8-8e1d-9cd44ee051e5.png)
![_20180130225001](https://user-images.githubusercontent.com/34188141/35572606-f0fafa10-060f-11e8-905c-63359bb33c10.png)

 

>

**Comment by drisso** [comment]
Hi @CcYyQq 

the error message is telling you that your `SummarizedExperiment` object contains numbers that are not integer. Since `zinbwave` is designed to work only with count data, we do not currently support data that are not integer counts.

**Comment by CcYyQq** [comment]
Thank you. 
I will try to refine the input expression matrix.
