### ISSUE TITLE
fixing gamma_mu or don't estimate intercepts?

### ISSUE THREAD

**Issue by gbiele** [drisso/zinbwave#15]
Hi,

I am running a tests with data simulated using zinbwave and find that, when fitting data, some variance that should be captured by W is captured by gamma_mu.

In particular, if I define a model ```zinbModel```
    
```

nS = 500 # sample size
    nG = 50  # number genes
    K  = 2   # number of latent factors
    W = matrix(rnorm(nS*K),ncol = K) 
    X = matrix(1, ncol = 1, nrow = nS)
    V = matrix(rnorm(nG), ncol = 1)
    mm = zinbModel(X = X,
                   V = V,
                   W = W,
                   gamma_mu = matrix(1, ncol = N),
                   ...) # omitting specification more parameters here

```

and simulate data and then run zinbFit:

```
    my_data = zinbSim(mm)
    SE = SummarizedExperiment(assays = list(counts=my_data$counts),
                              rowDat = data.frame(V),
                              colDat = data.frame(X))
    sf = zinbFit(seY,
             V = "~V",
             K = 2)

```
the resulting columns in ```W``` are correlated with the sample wise intercepts```sf@gamma_mu[1,]```, and weaker than expected correlated with columns in ```sf@W```. I write "weaker than expected" because I find that ```W``` correlates more strongly with the component scores obtained from a simple PCA on the count data simulated with zinbwave, which I find odd.

I assume, a reason for this could be that if in the data generating process there is no intercept in V, but the fitted zinbwave-model includes this intercept, the regression weights for this intercept capture variance that should be captired by other parts of the model (```W ```).

Hence, my question if one can run zinbFit without and intercept term in V.

Thanks in advance for any response!
Guido

**Comment by drisso** [comment]
Hi @gbiele 

you're right, if the data generating model doesn't include an intercept in V, the model itself should not include it.

You can achieve that by simply add a "-1" to the formula.

In your example, that would mean:
```{r}
  sf = zinbFit(seY,
             V = "~ V - 1",
             K = 2)
```

Let me know if this solves your problem.

Best,
Davide

**Comment by gbiele** [comment]
oops, I should have thought of that.
results are looking more reasonable now, though the simple PCA still recovers the latent factors as well as zinbwave (for the limited set of data I have simulated)
thanks for the quick response!
Best, Guido

**Comment by drisso** [comment]
Just as an additional comment on your simulation, sometimes increasing the value of epsilon will result in a better estimated W. The default value is good with many genes but may not be with only 50 genes like your simulation. Also, note that you're simulating essentially a rank 1 signal so K=1 might give you (possibly) better results.
