### ISSUE TITLE
zinbInitialize() fails if softImpute does not find low-rank matrix with rank NCOL(W)

### ISSUE THREAD

**Issue by drisso** [drisso/zinbwave#16]
In some cases, we encounter this error:

```{r}
 Error in W %*% alpha_pi : non-conformable arguments 
```

This happens in `zinbInitialize()` and specifically at https://github.com/drisso/zinbwave/blob/master/R/zinb_fit.R#L231

If `softImpute` finds a low-rank matrix of dimension < K, the line
https://github.com/drisso/zinbwave/blob/master/R/zinb_fit.R#L257
fails because the dimension of W and alpha are not compatible.

This should be solvable, by using a different initialization for W in case this happens. But what is a smart value for W in this case? (Or should we just give an error and suggest to run the model with K-1?)

**Comment by drisso** [comment]
@jpvert any suggestions about this issue?

**Comment by jpvert** [comment]
I can imagine two solutions:
- if the rank of W returned by softimpute is too small, just add columns of zeros to make sure at least the size of the matrices are compatible
- alternatively, iterate the call to softimpute by decreasing the lambda parameter (eg, lambda <- lambda/2), until the rank is ok. Decreasing lambda increases the rank of the solution.

**Comment by drisso** [comment]
Thanks @jpvert !

I will try to implement both and do a bit of testing to see which approach is best / most convenient. I will keep updating this thread.

**Comment by drisso** [comment]
I have implemented the second strategy in the develop branch. It passes all tests on my machine, but I'll keep testing it on real examples before merging to master.
