### ISSUE TITLE
zinbFit for simulated data when beta_pi and beta_mu are 0 in the generative model

### ISSUE THREAD

**Issue by gbiele** [drisso/zinbwave#21]
To test the application of zinbwave for a new domain I would like to analyze data where missingness is only due to `alpha_pi` and `W`, whereas `beta_pi` and `gamma_pi` are 0.
However, I cannot seem to figure out how to run `zinbFit` such that `beta_pi` and `gamma_pi` are constrained to be 0. For example `which_X_pi` has to be an integer and cannot simply be NULL to indicate that no parameters `beta_pi` are needed (looking at the source code showed me why that can’t work). 

I also tried to set the relevant penalty terms, e.g. `epsilon_beta_pi` to a large number, but this doesn’t work: I am not able to recover the correct parameter values. (Large penalties can constrain `gamma_pi` to very close to zero, but this does not work for `beta_pi`).

Importantly, the inability to constrain parameters in the desired way also leads to the inability accurately estimate the latent variables parameters in`W`.

QUESTION:
Is there a way in the current version of zinbwave to fix one or several of `beta_pi`, `gamma_pi`, `beta_mu` and  `gamma_mu` at 0, or would the underlying code need to be rewritten to make this possible?

I think this possibility would be generally useful, because one could then use AIC or BIC to test if these parameters are necessary for the model to obtain a good fit.``

**Comment by gbiele** [comment]
Found the answer:

beta_pi can be set to zero by adding  `which_X_pi = integer(0)` when calling zinbFit. (for gamma_mu: `which_V_mu = integer(0)`, and so forth).

**Comment by drisso** [comment]
Sorry that you had to find the answers by yourself! But I confirm that that's the correct method.
