### ISSUE TITLE
error when using large epsilon values

### ISSUE THREAD

**Issue by gbiele** [drisso/zinbwave#22]
The vignette on github suggests using large epsilon values between 1e6 and 1e13.
When I try using values in that range, or even much smaller ones (e.g. 1000), I am getting the error message

> Error: BiocParallel errors
>   element index: 1, 2, 3, 4, 5, 6, ...
>   first error: gradient in optim evaluated to length 2 not 1
> 

When I use the default epsilon = J, the model can be fitted, but now I am uncertain if I could get a better fit with a different regularization parameter.
Is it possible, that epsilon should not be very high if one has relatively few "genes"?

Relatedly: Would it make sense to set the regularization for W (epsilon_W) to 0 in order to maximize the variation in W? Or would the fitting become to unstable?

Here is the code to reproduce the error message

```
N = 250
K = 2
J = 9

set.seed(1)
W = matrix(rnorm(N*K),ncol = K) + 3
V = matrix(sort(rep(log(c(25,250,1000)),3)), nrow = J)
X = matrix(1, ncol = 1, nrow = N)
  
alpha_mu = matrix(rnorm(K*V),ncol = J, nrow = K)/15
alpha_pi = matrix(rnorm(K*V),ncol = J, nrow = K)
  
mup = rep(c(-4,-2,0),3)
for (v in 1:J) {
  y = scale(W %*% alpha_pi[,v]) + mup[v]
  lmfit = lm(y ~ -1 + W)
  alpha_pi[,v] = coefficients(lmfit)
}

mm = zinbModel(X = X,
               V = V,
               which_V_mu = 1L,
               which_X_mu = integer(0),
               which_X_pi = integer(0),
               which_V_pi = integer(0),
               W = W,
               gamma_mu = matrix(1,nrow = 1,ncol = N),
               alpha_mu = alpha_mu,
               alpha_pi = alpha_pi,
               zeta = log(rep(5,J)))
tmp = zinbSim(mm,seed = 1)
my_counts = tmp$counts
  
seY = SummarizedExperiment(assays = list(counts=my_counts),
                           rowDat = data.frame(V),
                           colDat = data.frame(X))

sf = zinbFit(seY,
                    V = "~ -1  + V",
                    K = 2,
                    stop.epsilon.optimize = 1e-05,
                    nb.repeat.initialize = 2,
                    maxiter.optimize = 50,
                    which_X_mu = integer(0),
                    which_X_pi = integer(0),
                    which_V_pi = integer(0),
                    epsilon = 1e7)  
```

**Comment by drisso** [comment]
Hi @gbiele,

the bug that you hit with such high value of epsilon is related to issue #16 and it's due to the initialization step. In particular, we use the `softImpute` function to get a low-rank approximation that we use to initialize `W`. When `epsilon` is too big, the rank of this approximation becomes lower than the number of factors and creates dimension problems in the subsequent matrix multiplications.

I'm still trying to find the best solution for this, but note that we do not suggest such large values of epsilon for all applications, but only for differential expression. In addition, `epsilon_W` is by default `epsilon / n` (see the details of `?zinbModel`) so keep that in mind if you want to change its default value. In general, the higher the dimensionality of the problem, the more important becomes the penalization, so if you have a small matrix like in your case, a small epsilon would make sense.

I will keep this open until I fix the initialization issue. Thanks for the report!

**Comment by drisso** [comment]
Thinking about it a little more, perhaps even in the case of small matrices, having a non-trivial penalization is important for stability. Think that even with just 250 observations and 9 genes like in your example, you end up with more than 500 parameters to estimate, so `epsilon=10` or even `100` could be beneficial.

**Comment by gbiele** [comment]
Thanks for the quick response!
When playing around with the epsilon values I also found out that setting `epsilon_W `(or `epsilon_alpha`) to very small values did not work well.
Thanks also for the reminder that 250 observations is not a lot when using 9 genes. I started with these small numbers so that the fitting wouldn't take too long. But I'll try larger sample sizes. (Our real data has more like 50000 samples and 75 observed variables, which are however not genes...)
From what you write, finding the right epsilon is not that easy, and it might make sense to run some simulations to look at the performance of different epsilon values (e.g. simulate 100 data sets, and for each try epsilon 1, 10, 50, 100, ... or similar, as criterion one could e.g. use squared deviations of "true" and estimated alpha_.. and W values.). That would of course take a while but with access to a cluster that's doable.

**Comment by PaigeVega** [comment]
Hi, @drisso

Are there any updates on choosing a value for epsilon?  I also get the error message when I use 1e6 or higher, but 1e5 is working for my dataset. 

Thanks! - Paige

**Comment by drisso** [comment]
Please see issue #16. This is the same issue.

**Comment by drisso** [comment]
@PaigeVega please try the version of the package in the develop branch and see if it solves your issue. Please, reply to issue #16 in case it doesn't!

Thanks!

**Comment by PaigeVega** [comment]
@drisso - it seems to be working now!  Thanks for the update.
