### ISSUE TITLE
Gene loadings 

### ISSUE THREAD

**Issue by bio-la** [drisso/zinbwave#26]
Hi Davide,
what would be a measure of gene loadings in the Zinb model when used as dimensionality reduction e.g. PCA - does it make sense to rank the 'genes that contribute the most' to the variability explained by the K component estimated (and have a measure of relevance of the K)? 
I am currently checking the R^2 between the known covariates/batch effects and the estimated Ks, to select them for downstream analyses, as it seems it's what you suggest to do in the paper anyway.
Does this make sense?
Thanks.

**Comment by drisso** [comment]
Hi,

I'm not sure what you mean by "genes that contribute the most to the variability". 

You can think of our model as a factor analysis model, so the `alpha` parameter will give you a sort of weight on how much each gene contributes to each factor (if that's your question). You can access the alpha parameter by using the `getAlpha_mu()` or `getAlpha_pi()` functions, depending on whether you want to look at the mean or at the zero inflation probability.

Does this answer your question?

**Comment by bio-la** [comment]
Yes, sorry, the way I formulated the question was definitely unclear. Thank you.
