### ISSUE TITLE
Core dump from RSEC()

### ISSUE THREAD

**Issue by davismcc** [drisso/zinbwave#3]
Hi Davide

I've been able to run `zinbwave` on my ~8800 cell dataset after rounding estimated counts to integers. It takes a while (~25 hrs), but works well as far as I can tell.

I'm now having a problem with `RSEC` (again, following the F1000 workflow). I'm running the commands below:
```
R> register(SerialParam())
R> se <- readRDS("../../data_processed/zinbwave/se_merged_qc_zinbwave.rds")
R> W <- colData(se)[, grepl("^W", colnames(colData(se)))]
R> W <- as.matrix(W)
R> seObj <- SummarizedExperiment(t(W), colData = colData(se))
R> register(SerialParam())
R> seObj
class: SummarizedExperiment
dim: 30 8818
metadata(0):
rownames(30): W1 W2 ... W29 W30
rowData names(0):
colnames(8818): 19776_1#100 19776_1#102 ... 22607_8#98 22607_8#99
colData names(176): salmon_version samp_type ... W29 W30
R> print(system.time(
 +     ceObj <- RSEC(seObj, k0s = 4:15, alphas = c(0.1),
 +                   betas = 0.8, dimReduce="none",
 +                   clusterFunction = "hierarchical01", minSizes = 1,
 +                   ncores = 1, isCount = FALSE,
 +                   dendroReduce = "none", dendroNDims = NA,
 +                   subsampleArgs = list(resamp.num = 100,
 +                                        clusterFunction = "kmeans",
 +                                        clusterArgs = list(nstart = 10)),
 +                   verbose = TRUE,
 +                   combineProportion = 0.7,
 +                   mergeMethod = "none", random.seed = 424242,
 +                   combineMinSize = 10)))
 Timing stopped at: 712 1437 3069
```

This results in R aborting with a core dump. I'm running in an interactive cluster job with 50Gb of memory, so reaching the memory limit would be surprising, but the only regular time I've seen this sort of error is upon hitting the job memory limit.

Is that the possible explanation here, or do you think something else is going on? 

Unfortunately I can't give you `sessionInfo` here, but I have had the same behaviour replicated a few times. 

Any suggestions would be very helpful!

Best
Davis

**Comment by drisso** [comment]
Hi @davismcc 

do you mind opening this issue in the [clusterExperiment package](https://github.com/epurdom/clusterExperiment) since this is not technically zinbwave's fault :)

BTW, 25 hours sounds like a really long time for 8800 cells... how many genes? And how many cores? What value of K?

It took 13 hours for me to run zinbwave on 68k PBMCs from 10x Genomics (with K=2).

[edit: I see now that you have K=30, that might be why it takes so long... I didn't realize increasing K had this huge cost!]
