### ISSUE TITLE
So very slow, could you develop speed-ups using, e.g., Rcpp?

### ISSUE THREAD

**Issue by chriscainx** [drisso/zinbwave#37]

**Comment by chriscainx** [comment]
https://sheffieldr.github.io/assets/slides/2017-05-speed_up_r_with_cpp-theo-michelot.pdf
This could be useful :)

**Comment by chriscainx** [comment]
https://github.com/fditraglia/econ722/blob/7b2cf6b54111144ad3786bad3e4d16f7cadbcf41/RcppArmadillo/ridge.cpp

**Comment by drisso** [comment]
Yes, I'm aware of Rcpp. 

I'm not sure how much faster it will be (optim is in C), but it's certainly something that we could look into (among other things).

If you're so frustrated by the speed, PR's are welcome... unfortunately, I don't do this as a full time job...

Also, note that the main problem with large datasets is not so much speed, but memory.
