### ISSUE TITLE
ZinbWave + RSEC error

### ISSUE THREAD

**Issue by siyao-liu** [drisso/zinbwave#42]
Hello,

I'm trying to run RSEC() on a W matrix (50 genes and 12170 cells) derived from ZinbWave. I got the error as below:

Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘primaryCluster’ for signature ‘"NULL"’

I also found a previous post on github related to this issue: #182

However, the issue was with the clusterMany() function. I wonder if the issue with the RSEC() function has also something to do with the memory? I tried adding the argument "largeDataset=TRUE" in the RSEC() function but it didn't solve the problem. Can anyone help? Thanks very much!

**Comment by drisso** [comment]
This is duplicated, continue at https://github.com/epurdom/clusterExperiment/issues/263
