### ISSUE TITLE
Bug in computeObservationWeights?

### ISSUE THREAD

**Issue by drisso** [drisso/zinbwave#43]
This line should be `zinbwg[zinbwg < 1e-15] <- 1e-15`

https://github.com/drisso/zinbwave/blob/6581bcc9f8554210f348e5f40bf09644365655f0/R/zinbwave.R#L48

am I right @koenvandenberge? I think I introduced this in the last release version...

**Comment by koenvandenberge** [comment]
Yes! This might explain the odd effects we've been seeing? Since all zeros got weight of 1e-15.
Sorry I did not notice this either.

**Comment by drisso** [comment]
Yeah, I think so... ugh! :(

I'll fix it in both devel and release ASAP!

**Comment by koenvandenberge** [comment]
Great, thank you!

**Comment by drisso** [comment]
This has been fixed in both release and devel
