### ISSUE TITLE
zinbwave Matrix error

### ISSUE THREAD

**Issue by cstrlln** [drisso/zinbwave#45]
Hello,
I'm trying to run zinbwave in a cluster and seems to run but I get a Matrix error:

> sce_cl2_zinb <- zinbwave(sce_cl2, K = 2, X = "~mouseID + Sex" , epsilon=1e12, BPPARAM=BiocParallel::MulticoreParam(8), verbose = TRUE)
Create model:
ok
Initialize parameters:

ok
Optimize parameters:
Iteration 1
penalized log-likelihood = -21740231789.945
After dispersion optimization = -21739843271.2819

   user  system elapsed 
  1.571   9.862 477.966 
After right optimization = -10876510949.4719
After orthogonalization = -13745479.7973216
   user  system elapsed 
  1.401  13.033 100.598 
After left optimization = -12633848.2457174
After orthogonalization = -12410537.8832695
Iteration 2
penalized log-likelihood = -12410537.8832695
After dispersion optimization = -12410537.8832695
   user  system elapsed 
  1.155   9.499 134.225 
After right optimization = -12379701.8727642
After orthogonalization = -12379673.1041869
   user  system elapsed 
  0.900   5.435  37.266 
After left optimization = -12378974.9080583
After orthogonalization = -12378974.4038585
Iteration 3
penalized log-likelihood = -12378974.4038585
After dispersion optimization = -12378974.4038585
   user  system elapsed 
  0.886   5.043  35.479 
After right optimization = -12377788.410242
After orthogonalization = -12377788.3266477
   user  system elapsed 
  1.208   7.518  42.181 
After left optimization = -12377733.3209309
After orthogonalization = -12377733.3209296
Iteration 4
penalized log-likelihood = -12377733.3209296
After dispersion optimization = -12377733.3209296
   user  system elapsed 
  1.067   6.529  49.023 
After right optimization = -12377381.0485549
After orthogonalization = -12377381.0388892
   user  system elapsed 
  0.975   4.738  55.937 
After left optimization = -12377367.3906731
After orthogonalization = -12377367.3906544
Iteration 5
penalized log-likelihood = -12377367.3906544
ok
Error in t.default(x) : argument is not a matrix

Otherwise I'm mostly interested in the weight values for using in edgeR.
please advice.

**Comment by jhong26** [comment]
I'm also getting a similar error..

**Comment by drisso** [comment]
Sorry for getting late to this. What version of zinbwave are you using? Can you produce a minimal running example illustrating this behavior?

**Comment by jhong26** [comment]
Thats for getting back Davide. I am using zinbwave version 1.6.0. My
purpose is to use zinbwave for DEseq2 on single cell data from a Seurat
object. I have two conditions; I have not added this metadata yet. I just
wanted to do a test run first. Here is the output:

# sub: Seurat object of single cell data
> z <- SingleCellExperiment(assays = list(counts = GetAssayData(object =
sub, slot = "counts")))
> z
class: SingleCellExperiment
dim: 6537 848
metadata(0):
assays(1): counts
rownames(6537): 2610015P09Rik AABR07001899.1 ... Zbtb32 Adam18
rowData names(0):
colnames(848): SuHx.PH1.SCR3_TGGGATATAAGA SuHx.PH1.SCR3_CCTCGATTAATA ...
  Control.PH2D2.SCR18_TATACGGGTTGA Control.PH2D2.SCR18_TGTCGTGAAGCC
colData names(0):
reducedDimNames(0):
spikeNames(0):
> BiocParallel::register(BiocParallel::SerialParam())
> sce_zinb <- zinbwave(z, K = 0, epsilon=1000, observationalWeights = TRUE,
BPPARAM=MulticoreParam(2), verbose=TRUE) #also tried with epsilon=1e13 and
got same error
Create model:
ok
Initialize parameters:
ok
Optimize parameters:
Iteration 1
penalized log-likelihood = -1478227.11696393
After dispersion optimization = -1418525.91743817
   user  system elapsed
  0.657   0.386  37.325
After right optimization = -1314985.34430378
After orthogonalization = -1314985.34430378
   user  system elapsed
  0.767   0.548  27.299
After left optimization = -1297233.90997914
After orthogonalization = -1297233.90997914
Iteration 2
penalized log-likelihood = -1297233.90997914
After dispersion optimization = -1297233.90997914
   user  system elapsed
  0.645   0.358  32.728
After right optimization = -1295467.12581696
After orthogonalization = -1295467.12581696
   user  system elapsed
  0.617   0.348  21.994
After left optimization = -1295107.94940988
After orthogonalization = -1295107.94940988
Iteration 3
penalized log-likelihood = -1295107.94940988
After dispersion optimization = -1295107.94940988
   user  system elapsed
  0.642   0.377  30.578
After right optimization = -1295010.39472818
After orthogonalization = -1295010.39472818
   user  system elapsed
  0.590   0.312  22.069
After left optimization = -1294978.88732346
After orthogonalization = -1294978.88732346
Iteration 4
penalized log-likelihood = -1294978.88732346
ok
* Error in t.default(x) : argument is not a matrix *

> sessionInfo()
R version 3.6.1 (2019-07-05)
...
 [1] Seurat_3.0.2                biomaRt_2.40.3              ggplot2_3.2.0

 [4] magrittr_1.5                scRNAseq_1.10.0             zinbwave_1.6.0

 [7] SingleCellExperiment_1.6.0  SummarizedExperiment_1.14.0
DelayedArray_0.10.0
-----
Any input would be much appreciated. Thank you!
Jason
...

**Comment by drisso** [comment]
Not sure what is going on here. Is `counts(z)` indeed of class `matrix`? (Rather than a sparseMatrix or other matrix representations?)

**Comment by CUsdevoe** [comment]
Was a solution for this error ever discovered? I am encountering the same problem with version 1.10.0

**Comment by drisso** [comment]
The likely error was that the assay of the SingleCellExperiment object was not of class `matrix`.

Please, check the class of your input object (e.g., `class(x)` or `class(assay(x))`).
