### ISSUE TITLE
Scanpy AnnData Object as Input

### ISSUE THREAD

**Issue by aditisk** [drisso/zinbwave#50]
Hello,

I am using Scanpy for analyzing our 10x data. Do you have any suggestions of how I could easily use data from Scanpy (AnnData object/h5ad format) as input in zinbwave ? 

This is what I tried so far:

- Converted from h5ad to Seurat object. 

- Converted this Seurat object to a SingleCellExperiement Object 
But when I try to use this SCE object, I get the following error message:

Error in .local(Y, ...) : 
  The input matrix should contain only whole numbers.

@drisso any thoughts on what the easiest way around this issue would be ? Any help from other users is highly appreciated.

Thank you.

**Comment by drisso** [comment]
Hi @aditisk 

the error message suggests that your matrix does not contain counts but something else (i.e., non-integer values). Zinbwave must be applied to raw unnormalized counts, are you giving as input something different? E.g., normalized data?

**Comment by aditisk** [comment]
Hi @drisso, I’m so sorry I missed your comment above. I’ll try again with raw data. Thanks.

**Comment by drisso** [comment]
OK, happy to reopen this if you're still having issues.
