### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by ChrisAi89** [drisso/zinbwave#51]
Hi,

I try to run the _zinbwave_ function on a data set created from single cell data processed with _SEURAT_ (see attachment). The function call looks as follows:

```
cd_cells_zinb <- zinbwave(sum_experimet, 
                          K = 10,
                          X = "~batch + nCount_RNA", 
                          verbose = TRUE)
```
The function output appears to be:
```
Create model:
ok
Initialize parameters:
Error in result[[njob]] <- value :
  attempt to select less than one element in OneIndex
In addition: Warning messages:
1: In simpute.als(x, J, thresh, lambda, maxit, trace.it, warm.start,  :
  Convergence not achieved by 100 iterations
2: In parallel::mccollect(wait = FALSE, timeout = 1) :
  3 parallel jobs did not deliver results
```

I have no idea, why that specific error occurs. If I get it right, the function calls a non-existent or empty list entry. Since the input data is a object of class "SummarizedExperiment" and from point of view correctly assembled.
Any ideas guys?

Cheers!
[sum_experimet.RData.zip](https://github.com/drisso/zinbwave/files/4128943/sum_experimet.RData.zip)

**Comment by ChrisAi89** [comment]
Figured the problem out: parallelization did not work due to not updated C-libraries. 
Lesson learned: keep your dependencies up to date!

**Comment by genec1** [comment]
Which C libraries did you need to update?
