### ISSUE TITLE
Documentation error for "observationalWeights"

### ISSUE THREAD

**Issue by rupertoverall** [drisso/zinbwave#56]
As mentioned in [Issue #47](https://github.com/drisso/zinbwave/issues/47#issuecomment-557299892), the documentation in the [BioConductor vignette](https://bioconductor.org/packages/devel/bioc/vignettes/zinbwave/inst/doc/intro.html#introduction) still states "Since version 1.1.5, zinbwave computes the observational weights by default." (version 1.10.0 retrieved 2020.06.25) although the man page (correctly) states that "observationalWeights = FALSE" is the default. 
This does tend to lead to a wild goose chase when following the tutorial step-by-step for the first time.

**Comment by drisso** [comment]
Thanks for pointing this out! I've fixed the vignette in version 1.11.1.
