### ISSUE TITLE
Latent factors for differential expression

### ISSUE THREAD

**Issue by vincr04** [drisso/zinbwave#58]
Hi everyone, 

I am measuring differential expression between two conditions in 10X data, using zinbwave and DESeq2. I am using K=2 in zinbwave as there are some latent factors (e.g. library size) that I would like to infer from the data. Now, would it make sense to include W1 (as calculated with zinbwave) in the DESeq2 design model (something like `design <- model.matrix(~condition + reducedDim(exp, "zinbwave")[,1])`? Or is W somehow already reflected in the observational weights, in which case including it in the model would be redundant? 

Similarly, as I use the LRT test in DESeq2 should I include W in the reduced formula?

Many thanks for your input!
Vincent

**Comment by drisso** [comment]
Closing this as it's discussed at https://support.bioconductor.org/p/132580/#132595
