### ISSUE TITLE
W2=0 when calculating two latent variables

### ISSUE THREAD

**Issue by vincr04** [drisso/zinbwave#59]
Hi,
I have some 10X single-cell data and am using zinbwave to infer latent variables. I realised that when using K=2 in zinbFit, W1 values are between ~-0.2 and ~0.2, but W2 values are all 0.
My code: 
`design <- model.matrix(~se$sex1*se$stim)`
`zinb <- zinbFit(Y=se, X=design, epsilon=1e6, K=2, verbose=T, BPPARAM=MulticoreParam(8))`
`se_zinb <- zinbwave(Y=se, X=design, epsilon=1e6, fitted_model=zinb, K=2, verbose=T, observationalWeights=T)`
`head(reducedDim(se_zinb))`
![Screenshot 2020-07-15 at 17 46 38](https://user-images.githubusercontent.com/39629190/87572232-27fc7400-c6c3-11ea-888e-f115a04a93b9.png)

You can download the data here: https://github.com/vincr04/variousdata/blob/master/se.Robj

Somehow if I choose K=3 the problem doesn't occur...
`zinb <- zinbFit(Y=se, X=design, epsilon=1e6, K=3, verbose=T, BPPARAM=MulticoreParam(8))`
`se_zinb <- zinbwave(Y=se, X=design, epsilon=1e6, fitted_model=zinb, K=3, verbose=T, observationalWeights=T)`
`head(reducedDim(se_zinb))`
![Screenshot 2020-07-15 at 17 47 50](https://user-images.githubusercontent.com/39629190/87572398-5ed28a00-c6c3-11ea-9bdf-ca702f5c4e6b.png)

 Is this a bug, or did I do something wrong?

**Comment by drisso** [comment]
Thanks, this definitely looks like a bug, I will have a look at the data and update you here.

**Comment by drisso** [comment]
I can confirm that I'm able to reproduce your example. This is quite puzzling, but I'm looking into it.

**Comment by drisso** [comment]
I found the bug. This was due to `softImpute` sometimes returning a singular value of 0. I've fixed it in version 1.11.6.
