### ISSUE TITLE
zinbwave on integrated data set

### ISSUE THREAD

**Issue by yeroslaviz** [drisso/zinbwave#62]
I would like to better understand how to apply the zinbwave workflow onto my integrated data set.

I have four datasets, from two different conditions in replicates.
In Order to first find the most variable genes i have done in seurat the standard workflow and used the SCTransform as well as the integrateData step to combine the four sets in to seurat object.

Now O would like to test try to apply the zinbwave method to the data and find differential expressed genes between my two conditions.

Would it makes more sense to re-run the complete workflow from the beginning or maybe it is better to take the genes seurat has found to be variable after the integration (with FindVariableFeatures).

thanks

Assa

**Comment by drisso** [comment]
Starting from Seurat's most variable genes is probably what I would do (at least as a first pass) since you already have them.

I would bother going back from the beginning only if the results of zinbwave are unexpected.
