### ISSUE TITLE
Error in zinbwave

### ISSUE THREAD

**Issue by ZHIDIHUAYUAN** [drisso/zinbwave#63]
Hi, I have a problem in which I am trying to use the zinbwave package for differential expression analysis from scRNAseq data.
My code is: cluster0_obwt_zinb <- zinbwave(cluster0_obwt_sum, K = 0, epsilon=1e12,observationalWeights=TRUE,BPPARAM=SerialParam())
Error in zinbInitialize(m, Y, nb.repeat = nb.repeat.initialize, BPPARAM = BPPARAM) :
  Gene 4 has only 0 counts!
When I checked zero counts:
t<-rowSums(assay(cluster0_obwt_sum)==0)
summary(t)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
      0    1790    2337    2027    2487    2495
It shows that there is no genes that have only 0 counts.

**Comment by yeroslaviz** [comment]
It is difficult to see what you mean, when the message is not curated. Pls use the code option for your code.

Did you have a look at `Gene 4`?

From what I see you do have genes with `rowSums ==0`. The summary states the the min-value is `0`, which imply that there are 0-values in the vector. Did you use some kind of filtering in your analysis?

e.g. (from the vigentte)

`filter <- rowSums(assay(fluidigm)>5)>5`
