### ISSUE TITLE
Negative values in normalizedValues output

### ISSUE THREAD

**Issue by agranado** [drisso/zinbwave#67]
I am trying to use the normalizedValues from Zinbwave for downstream analysis and I noticed that the matrix contains several cell-gene data points with negative values. Is this correct? Is there a way to get normalized counts from zinbwave to correct the dropout and then use them for downstream analysis?

**Comment by drisso** [comment]
Hi @agranado,

the normalizedValues are returned by zinbwave only for the purpose of data exploration and graphical display, their use in downstream analysis is untested and not recommended. Our suggested workflow is to base downstream unsupervised analyses on the latent factors W and the supervised analyses on edgeR/DESeq2 with weights.

There are many other methods that can be used to correct for dropouts, but not zinbwave.

**Comment by agranado** [comment]
Hi @drisso 
Thanks a lot for your reply! I understand so we will keep the W for visualization and clustering. 

Thanks a lot.
