### ISSUE TITLE
Meaning of the weights

### ISSUE THREAD

**Issue by RonjaJohnen** [drisso/zinbwave#69]
Hello,
I have a rather general question about the weights and the function "computeObservationalWeights". Unfortunately, I could not find an explanation for the meaning of the weights. Can you explain to me what the motivation is for using the weights? And why are the weights calculated the way you did?

Thank you in advance for your help.

**Comment by drisso** [comment]
The best way to understand the logic of the weights and how/why they work is reading our paper:
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1406-4

Happy to answer specific questions if things are still unclear, just reopen the issue.

**Comment by RonjaJohnen** [comment]
Thanks for pointing me to the paper! I somehow missed it.
