### ISSUE TITLE
unable to find an inherited method for function ‘zinbFit’ for signature ‘"data.frame"’

### ISSUE THREAD

**Issue by eltonjrv** [drisso/zinbwave#72]
Dear ZINBWaVe team,

I'm stuck on this S4-related error message and wonder why, as everything seems to be okay with my SCE class S4-defined object (A1Bmtx_sce.keep).

################
> A1Bmtx_sce.keep
class: SingleCellExperiment 
dim: 13966 271111 
metadata(0):
assays(1): counts
rownames(13966): LINC00115 NOC2L ... MT-ND6 MT-CYB
rowData names(0):
colnames(271111): SRR7666705 SRR7666706 ... TTTGTCAAGCTGAACG
  TTTGTCACAATCGGTT
colData names(3): cells batch Biological_Condition
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):
> isS4(A1Bmtx_sce.keep)
[1] TRUE
> A1Bzinb <- zinbwave(A1Bmtx_sce.keep, K=9, X="~batch", epsilon=1e12, BPPARAM=BiocParallel::SnowParam(), observationalWeights=TRUE)
**Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘zinbFit’ for signature ‘"data.frame"’**
################

Any help will be much appreciated,
Thanks in advance,
Elton

**Comment by eltonjrv** [comment]
And if I do as.matrix on the 'Y', I get the following:

A1Bzinb <- zinbwave(as.matrix(A1Bmtx_sce.keep), K=9, X="~batch", epsilon=1e12, BPPARAM=BiocParallel::SnowParam(), observationalWeights=TRUE)
**Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'Y' in selecting a method for function 'zinbwave': error in evaluating the argument 'x' in selecting a method for function 'as.matrix': no method for coercing this S4 class to a vector**

**Comment by drisso** [comment]
Hi @eltonjrv

`as.matrix()` would not work in this case as there is no method to coerce a SingleCellExperiment into a matrix.

What is the class of `assay(A1Bmtx_sce.keep)`?

**Comment by eltonjrv** [comment]
Thanks for your prompt reply.
It's a data frame.

class(assay(A1Bmtx_sce.keep))
[1] "data.frame"

**Comment by drisso** [comment]
If you turn that into a matrix, with something like:
```{r}
assay(A1Bmtx_sce.keep) <- as.matrix(assay(A1Bmtx_sce.keep))
```
everything should work (hopefully!).

**Comment by eltonjrv** [comment]
I'm getting memory error, cause this data is huge!
I'll start a new R session.
Please bear with me.
Thanks

**Comment by eltonjrv** [comment]
I'm having to reload 114 public datasets to recreate A1Bmtx.
Bummer! :-/
It's gonna take a while

**Comment by eltonjrv** [comment]
It seems the matrix class problem is fixed, cause it's now giving me a 'not enough memory' error while attempting to run zinbwave:

A1Bzinb <- zinbwave(A1Bmtx_sce, K=9, X="~batch", epsilon=1e12, BPPARAM=BiocParallel::SnowParam(), observationalWeights=TRUE)
**Error: cannot allocate vector of size 28.2 Gb**

Solution: After opening a fresh R session and reloading all my datasets, I created the A1Bmtx_sce with the following:
A1Bmtx_sce = SingleCellExperiment(assays = list(counts = **as.matrix**(A1Bmtx)), colData=colDataA1B)

I've now submitted my zinb.R as job script to the cluster, with the hope that having a private node to run it will solve the memory issue.

I'll keep you posted!

**Comment by eltonjrv** [comment]
Ah, forgot to say that:
class(assay(A1Bmtx_sce))
[1] "matrix" "array"

**Comment by drisso** [comment]
Thanks for reporting back with the solution.
